# Generated by Django 5.1.6 on 2025-02-24 17:43

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="event",
            name="date",
        ),
        migrations.AddField(
            model_name="event",
            name="end_date",
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
