# Generated by Django 5.1.6 on 2025-03-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0003_event_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="event_images/"),
        ),
    ]
