# Generated by Django 4.2.19 on 2025-03-31 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="attendance",
            name="status",
            field=models.CharField(
                choices=[
                    ("going", "Going"),
                    ("can go", "Can Go"),
                    ("not going", "Not Going"),
                ],
                max_length=20,
            ),
        ),
    ]
