# Generated by Django 5.1.6 on 2025-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0008_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Enter a street address or place name",
                max_length=255,
            ),
        ),
    ]
