# Generated by Django 5.1.6 on 2025-05-28 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0009_event_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(help_text="Enter a title", max_length=200),
        ),
    ]
