# Generated by Django 4.2.19 on 2025-05-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0010_alter_event_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="bio",
            field=models.TextField(blank=True, max_length=250),
        ),
    ]
