# Generated by Django 5.1.6 on 2025-05-31 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0011_alter_profile_bio"),
        ("ETA", "0011_inviterequest"),
    ]

    operations = []
