# Generated by Django 4.2.19 on 2025-06-01 15:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0013_friendship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Friendship",
        ),
    ]
