# Generated by Django 5.1.6 on 2025-06-01 15:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0013_tag_tagcategory_event_tags_tag_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=30),
        ),
    ]
