# Generated by Django 5.1.6 on 2025-06-01 18:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0014_alter_tag_name"),
        ("ETA", "0014_delete_friendship"),
    ]

    operations = []
