# Generated by Django 5.1.6 on 2025-06-02 14:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ETA", "0015_merge_0014_alter_tag_name_0014_delete_friendship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
